In [1]:
numbers = [10, 20, 30, 40, 50]
print("List:", numbers)
print("List_type", type(numbers))
print("First element:", numbers[0])
print("Last element:", numbers[-1])
print("Length of list:", len(numbers))

# Changing element using indexing
numbers[2] = 99
print("After change:", numbers)
#append element
numbers.append(10)
# Iterating over list
print("Iterating over list:")
for n in numbers:
    print(n)

List: [10, 20, 30, 40, 50]
List_type <class 'list'>
First element: 10
Last element: 50
Length of list: 5
After change: [10, 20, 99, 40, 50]
Iterating over list:
10
20
99
40
50
10


In [2]:
# Creating 2D list
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("2D List (Matrix):")
for row in matrix:
    print(row)
#as like c.
row,col= (3,3)
for i in range(row):
    for j in range(col):
        print(matrix[i][j]," ",end="")
    print()
    
# Access individual element
print("Element at [1][2]:", matrix[1][2])  # row 1, column 2 → value 6

# Changing element
matrix[0][0] = 100
print("After change:", matrix)

# Nested loops for 2D list
print("Iterating through 2D list:")
for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        print(f"matrix[{i}][{j}] =", matrix[i][j])

2D List (Matrix):
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
1  2  3  
4  5  6  
7  8  9  
Element at [1][2]: 6
After change: [[100, 2, 3], [4, 5, 6], [7, 8, 9]]
Iterating through 2D list:
matrix[0][0] = 100
matrix[0][1] = 2
matrix[0][2] = 3
matrix[1][0] = 4
matrix[1][1] = 5
matrix[1][2] = 6
matrix[2][0] = 7
matrix[2][1] = 8
matrix[2][2] = 9


In [3]:
# range(stop)
for i in range(5):
    print(i, end=" ")  # prints 0 1 2 3 4
print()

# range(start, stop)
for i in range(3, 8):
    print(i, end=" ")  # prints 3 4 5 6 7
print()

# range(start, stop, step)
for i in range(2, 10, 2):
    print(i, end=" ")  # prints 2 4 6 8
print()

0 1 2 3 4 
3 4 5 6 7 
2 4 6 8 


In [5]:
import numpy as np

# Creating numpy array
arr = np.array([10, 20, 30, 40, 50])
print("NumPy Array:", arr)
print("Type:", type(arr))
print("Data Type:", arr.dtype)
print("Shape:", arr.shape)
print("Length:", len(arr))

# Access and modify
print("First element:", arr[0])
arr[1] = 99
print("Modified array:", arr)

# Looping through numpy array
for value in arr:
    print("Value:", value)
for i in range(len(arr)):
    print("Value:",arr[i])

NumPy Array: [10 20 30 40 50]
Type: <class 'numpy.ndarray'>
Data Type: int64
Shape: (5,)
Length: 5
First element: 10
Modified array: [10 99 30 40 50]
Value: 10
Value: 99
Value: 30
Value: 40
Value: 50
Value: 10
Value: 99
Value: 30
Value: 40
Value: 50


In [6]:
# Creating 2D numpy array
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("2D Array:\n", mat)
print("Shape (rows, cols):", mat.shape)

# Accessing element
print("Element [1,2]:", mat[1, 2])

# Modifying
mat[0, 0] = 100
print("After change:\n", mat)

# Loop through 2D numpy array
print("Row-wise iteration:")
for row in mat:
    print(row)

print("Each element with indices:")
for i in range(mat.shape[0]):       # number of rows
    for j in range(mat.shape[1]):   # number of cols
        print(f"mat[{i},{j}] =", mat[i, j])

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape (rows, cols): (3, 3)
Element [1,2]: 6
After change:
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]
Row-wise iteration:
[100   2   3]
[4 5 6]
[7 8 9]
Each element with indices:
mat[0,0] = 100
mat[0,1] = 2
mat[0,2] = 3
mat[1,0] = 4
mat[1,1] = 5
mat[1,2] = 6
mat[2,0] = 7
mat[2,1] = 8
mat[2,2] = 9


In [7]:
ones = np.ones((2, 3))
print("Ones array:\n", ones)

seq = np.arange(0, 10, 2)
print("Array from np.arange:", seq)

zeros_1d = np.zeros(5,dtype=int)  # 5 elements → 1D array
print("1D zeros array:", zeros_1d)
print("Shape:", zeros_1d.shape)  

zeros_2d = np.zeros((3, 4))  # 3 rows, 4 columns
print("2D zeros array:\n", zeros_2d)
print("Shape:", zeros_2d.shape)  # (3, 4)

Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array from np.arange: [0 2 4 6 8]
1D zeros array: [0 0 0 0 0]
Shape: (5,)
2D zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)


In [9]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.dot(A, B)

print(C)

[[19 22]
 [43 50]]


In [10]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
AT = np.transpose(A)
print(AT)

[[1 4]
 [2 5]
 [3 6]]


In [4]:
import numpy as np

lst = [1, 2, 3, 4]

arr = np.array(lst)

print(arr)

[1 2 3 4]


In [8]:
new_list = arr.tolist()

print(new_list)

[10, 99, 30, 40, 50]


In [11]:
import math
angle_degrees=45
theta = math.radians(angle_degrees)
print(math.cos(theta))
print(math.sin(theta))

0.7071067811865476
0.7071067811865476
